import Foundation

enum LocalizationKey: String, CaseIterable {
  case appTitle = "app.title"
  case supportedGuest = "label.supportedGuest"
  case emptyTitle = "home.empty.title"
  case emptySubtitle = "home.empty.subtitle"
  case createVM = "action.createVM"
  case selectISO = "action.selectISO"
  case startVM = "action.startVM"
  case stopVM = "action.stopVM"
  case cancel = "action.cancel"
  case notInstalled = "status.notInstalled"
  case installing = "status.installing"
  case stopped = "status.stopped"
  case running = "status.running"
  case needsAttention = "status.needsAttention"
  case details = "label.details"
  case console = "label.console"
  case cpu = "label.cpu"
  case memory = "label.memory"
  case disk = "label.disk"
  case installMedia = "label.installMedia"
  case network = "label.network"
  case bootSource = "label.bootSource"
  case networkNAT = "value.network.nat"
  case bootInstallMedia = "value.boot.installMedia"
  case bootDisk = "value.boot.disk"
  case consoleEmptyTitle = "console.empty.title"
  case consoleEmptySubtitle = "console.empty.subtitle"
  case createUnavailable = "home.createUnavailable"
  case deleteConfirmationTitle = "delete.confirmation.title"
  case deleteConfirmationMessage = "delete.confirmation.message"
  case isoMissing = "error.isoMissing.title"
  case isoInvalid = "error.isoInvalid.title"
  case storageLow = "error.storageLow.title"
  case configInvalid = "error.configInvalid.title"
  case startFailed = "error.startFailed.title"
  case chooseAnotherISO = "action.chooseAnotherISO"
  case freeSpaceRetry = "action.freeSpaceRetry"
  case editSettings = "action.editSettings"
  case retryStart = "action.retryStart"
  case viewLogs = "action.viewLogs"
  case deleteVM = "action.deleteVM"
}

final class AppBundleMarker: NSObject {}
